CREATE TABLE news(
    news_id INT NOT NULL AUTO-INCREMENT
);

LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/news.csv'
INTO TABLE news
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 ROWS;